"""
Django settings for VulnAssesor project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%&jdbju&m41trxw#8o*of#53ri#txy59+cnwm8!89h2z3-b54r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Dashboard',
    'SAST',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VulnAssesor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'SAST.context_processors.user_projects',
            ],
        },
    },
]

WSGI_APPLICATION = 'VulnAssesor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('USE_SQLITE', 'False') == 'True':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_NAME', 'vulnassesor_db'),
            'USER': os.environ.get('POSTGRES_USER', 'vulnassesor'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'strongpassword'),
            'HOST': os.environ.get('POSTGRES_HOST', 'db'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Static Files
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Celery Configuration
# This points to the 'redis' service in docker-compose.yml
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# SAST tool-driven scan settings
SAST_SCAN_MAX_TOOL_CALLS = int(os.environ.get('SAST_SCAN_MAX_TOOL_CALLS', '24'))
SAST_SCAN_MAX_SEARCH_RESULTS = int(os.environ.get('SAST_SCAN_MAX_SEARCH_RESULTS', '30'))
SAST_SCAN_MAX_READ_LINES = int(os.environ.get('SAST_SCAN_MAX_READ_LINES', '160'))
SAST_SCAN_MAX_DIRECTORY_ENTRIES = int(os.environ.get('SAST_SCAN_MAX_DIRECTORY_ENTRIES', '200'))
SAST_SCAN_MAX_TOOL_RESULT_BYTES = int(os.environ.get('SAST_SCAN_MAX_TOOL_RESULT_BYTES', '12000'))
SAST_SCAN_SOFT_CONTEXT_TOKENS = int(os.environ.get('SAST_SCAN_SOFT_CONTEXT_TOKENS', '8000'))
SAST_SCAN_HARD_CONTEXT_TOKENS = int(os.environ.get('SAST_SCAN_HARD_CONTEXT_TOKENS', '12000'))
SAST_SCAN_IGNORED_DIRECTORIES = [
    '.git',
    'node_modules',
    'dist',
    'build',
    'coverage',
    '.venv',
    'venv',
    '__pycache__',
    '.mypy_cache',
    '.pytest_cache',
    '.tox',
    '.idea',
    '.vscode',
]
SAST_SCAN_ALLOWED_EXTENSIONS = [
    '.py',
    '.js',
    '.jsx',
    '.ts',
    '.tsx',
    '.html',
    '.css',
    '.java',
    '.c',
    '.cpp',
    '.cc',
    '.go',
    '.rs',
    '.php',
    '.rb',
    '.cs',
    '.json',
    '.yaml',
    '.yml',
    '.toml',
    '.ini',
    '.env',
    '.sql',
    '.sh',
    '.xml',
]
