# Generated by Django 5.2.8 on 2025-11-10 13:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_nucleitemplate_scanjob_scanresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.IntegerField(default=600, help_text='Scan timeout in seconds (60-3600)', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(3600)])),
                ('rate_limit', models.IntegerField(default=150, help_text='Maximum requests per second (1-1000)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('concurrency', models.IntegerField(default=25, help_text='Number of concurrent templates to run (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('silent_mode', models.BooleanField(default=True, help_text='Hide banner and progress bar')),
                ('no_color', models.BooleanField(default=True, help_text='Disable colored output')),
                ('jsonl_output', models.BooleanField(default=True, help_text='Output results as JSON Lines (required for parsing)')),
                ('retries', models.IntegerField(default=1, help_text='Number of times to retry a failed request (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('follow_redirects', models.BooleanField(default=True, help_text='Follow HTTP redirects')),
                ('custom_args', models.TextField(blank=True, help_text="Additional custom Nuclei arguments (e.g., '-proxy http://proxy:8080')")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nuclei_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nuclei Configuration',
                'verbose_name_plural': 'Nuclei Configuration',
            },
        ),
    ]
