# Generated by Django 5.2.8 on 2025-11-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scanjob',
            new_name='Dashboard_s_created_8f9d3f_idx',
            old_name='Dashboard_s_created_d63f91_idx',
        ),
        migrations.RenameIndex(
            model_name='scanjob',
            new_name='Dashboard_s_status_1797fe_idx',
            old_name='Dashboard_s_status_8a7c5e_idx',
        ),
        migrations.RenameIndex(
            model_name='scanjob',
            new_name='Dashboard_s_celery__5ce398_idx',
            old_name='Dashboard_s_celery__9e5d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='scanresult',
            new_name='Dashboard_s_job_id_f67d66_idx',
            old_name='Dashboard_s_job_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='scanresult',
            new_name='Dashboard_s_severit_000dc2_idx',
            old_name='Dashboard_s_severit_d4e5f6_idx',
        ),
    ]
