# Generated by Codex on 2026-04-29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_rename_dashboard_s_created_d63f91_idx_dashboard_s_created_8f9d3f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Claude'), ('deepseek', 'DeepSeek')], default='openai', help_text='AI provider used for SAST scans, fix generation, and verification.', max_length=20)),
                ('scan_model', models.CharField(default='gpt-5-nano', max_length=120)),
                ('fix_model', models.CharField(default='gpt-5-nano', max_length=120)),
                ('verify_model', models.CharField(default='gpt-5-nano', max_length=120)),
                ('openai_api_key_env_var', models.CharField(default='OPENAI_API_KEY', max_length=120)),
                ('anthropic_api_key_env_var', models.CharField(default='ANTHROPIC_API_KEY', max_length=120)),
                ('deepseek_api_key_env_var', models.CharField(default='DEEPSEEK_API_KEY', max_length=120)),
                ('openai_base_url', models.URLField(blank=True, default='')),
                ('anthropic_base_url', models.URLField(blank=True, default='')),
                ('deepseek_base_url', models.URLField(default='https://api.deepseek.com')),
                ('max_output_tokens', models.IntegerField(default=4096, help_text='Maximum tokens returned by AI providers where supported.', validators=[django.core.validators.MinValueValidator(512), django.core.validators.MaxValueValidator(200000)])),
                ('request_timeout', models.IntegerField(default=120, help_text='Provider request timeout in seconds.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configuration',
            },
        ),
    ]
