# Generated by Django 5.2.8 on 2025-11-22 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SASTFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('line_number', models.IntegerField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code_snippet', models.TextField()),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('ai_fix_code', models.TextField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('source_zip', models.FileField(blank=True, null=True, upload_to='projects/zips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('root_directory', models.CharField(blank=True, max_length=512, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SASTFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_code', models.TextField()),
                ('explanation', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fix', to='SAST.sastfinding')),
            ],
        ),
        migrations.CreateModel(
            name='SASTScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLONING', 'Cloning'), ('SCANNING', 'Scanning'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('commit_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('scan_type', models.CharField(choices=[('FULL', 'Full Scan'), ('INCREMENTAL', 'Incremental Scan')], default='FULL', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='SAST.project')),
            ],
        ),
        migrations.AddField(
            model_name='sastfinding',
            name='scan_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='SAST.sastscanjob'),
        ),
    ]
