# Generated by Django 5.2.8 on 2025-11-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLONING', 'Cloning'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
