# Generated by Django 5.2.8 on 2025-11-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAST', '0002_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sastscanjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLONING', 'Cloning'), ('SCANNING', 'Scanning'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
