# Generated by Django 5.2.8 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAST', '0003_alter_sastscanjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sastscanjob',
            name='agent_run_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sastfix',
            name='end_line',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sastfix',
            name='scope',
            field=models.CharField(choices=[('SNIPPET', 'Snippet'), ('FILE', 'File')], default='SNIPPET', max_length=20),
        ),
        migrations.AddField(
            model_name='sastfix',
            name='start_line',
            field=models.IntegerField(default=1),
        ),
    ]
