# Generated by Django 5.2.13 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAST', '0004_sastscanjob_agent_run_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ingestion_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('CLONING', 'Cloning'),
                    ('READY', 'Ready'),
                    ('CANCELLED', 'Cancelled'),
                    ('FAILED', 'Failed'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
